config/routes.rb
class AuthConstraint
  def matches?(request)
    request.session[:user_id].present?
  end
end

Rails.application.routes.draw do

  constraints(AuthConstraint.new) do
    root to: 'bulbs#index'
  end

  get 'sessions/create'

  get 'users/home'
  post 'users/home' => 'bulbs#create'

  get 'users/create'

  get 'bulbs/index'
  post 'bulbs/index' => 'bulbs#comment'
  patch 'bulbs/increment/:id' => 'bulbs#increment_likes'

  get 'bulbs/create'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', :to => 'users#failure'

  get 'schedules/index' => 'schedules#get_10_events'

  root to: 'pages#index'

end

app/models/bulb.rb
class Bulb < ApplicationRecord
  validates :bright,  presence: true
  validates :dim, presence: true
  validates :blocked, presence: true
  validates :panic_score, format: { with: /\d/ }

  belongs_to :user
  has_many :comments

end

app/controllers/bulbs_controller.rb
class BulbsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index

    data = []

    @all_bulbs = Bulb.all.where(is_deleted: false)

    @all_bulbs.each do |bulbs|
      bulb_id = bulbs.id
      bulb_owner = bulbs.user.name
      bulb_created = bulbs.created_at
      bright_bulb = bulbs.bright
      dim_bulb = bulbs.dim
      blocked = bulbs.blocked
      likes = bulbs.likes
      panic_score = bulbs.panic_score
      comments = bulbs.comments.where(bulb_id: bulbs.id).all

      data << { "bulb_id" => bulb_id, "bulb_created" => bulb_created, "bulb_writer" => bulb_owner, "bright" => bright_bulb, "dim" => dim_bulb, "blocked" => blocked, "likes" => likes, "panic_score" => panic_score, "comment_data" => comments}
    end

    data = data.sort_by { |bulb| bulb["bulb_created"]}.reverse

    respond_to do |format|
      format.json { render json: data }
      format.html { render :index }
    end
  end

  def create
    @bulb = Bulb.new(
      user_id: current_user.id,
      bright: params['bright'],
      dim: params['dim'],
      blocked: params['blocked'],
      panic_score: params['panic_score']
    )
    respond_to do |format|
      if @bulb.valid?
        @bulb.save
        :created
      else
        format.json { render json: @bulb.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def increment_likes
    bulb = Bulb.find(params['id'])
    bulb.increment!(:likes)
    status 200
  end

  def comment
    @comment = Comment.new(
      user_id: current_user.id,
      comment: params['comment'],
      bulb_id: params['bulb_id']
    )
    respond_to do |format|
      if @comment.valid?
        @comment.save
        :created
      else
        format.json { render json: @comment.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  private

  def bulb_params
    params.require(:bulb).permit(:id, :bright, :dim, :blocked, :likes, :panic_score)
  end
end

app/helpers/bulbs_helper.rb
module BulbsHelper
end

app/views/bulbs/create.html.erb
<h1>Bulbs#create</h1>
<p>Find me in app/views/bulbs/create.html.erb</p>

app/views/bulbs/index.html.erb
<div class="bulbsContainer" ng-controller="BulbsIndexController as timeline">

    <nav class="userHomeNav">

        <div class="title">
            <div class="yellow"></div>
            StandUp<%= image_tag("lightbulb.png", :alt => "Idea by Davo Sime from the Noun Project", :class => "navIcon") %>
        </div>

        <ul>
            <li><%= link_to "Home", users_home_path %></li>
            <li><%= link_to "All Bulbs", bulbs_index_path%></li>
        </ul>

    </nav>

    <div class="switchContainer" ng-click="timeline.toggleLightSwitch()">

        <div class="on" ng-show="timeline.on">
            <%= image_tag("switchOff.png", :alt => "switch by Felix Westphal from the Noun Project", :class => "switch") %>
        </div>

        <div class="off" ng-hide="timeline.on">
            <%= image_tag("switchOn.png", :alt => "switch by Felix Westphal from the Noun Project", :class => "switch on") %>
        </div>

    </div>

    <div class="bulbCard" ng-repeat="bulb in timeline.allBulbs">

        <ul class="bulbList">

            <li>
                <p>{{bulb.bulb_writer}}</p>
            </li>

            <li>
                <p class='likes' ng-hide="bulb.show" ng-model="bulb.likes">Likes:
                    {{bulb.likes}}</p>
                <p class='likes' ng-show="bulb.show">Likes:
                    {{timeline.newLike}}</p>
                <button type="button" name="likeBtn" class="likeBtn" ng-click="timeline.incrementLikes(bulb, bulb.likes, bulb.bulb_id)">Like</button>
            </li>

            <li>
                <%= image_tag("brightbulb.png", :alt => "lamp by Elves Sousa from the Noun Project", :class => "bulbIcon") %>
                <p>{{bulb.bright}}</p>
            </li>

            <li>
                <%= image_tag("dimbulb.png", :alt => "lamp by Elves Sousa from the Noun Project", :class => "bulbIcon") %>
                <p>{{bulb.dim}}</p>
            </li>

            <li>
                <%= image_tag("blocker.png", :alt => "wall by TDL-LONDON from the Noun Project", :class => "bulbIcon") %>
                <p>{{bulb.blocked}}</p>
            </li>

            <li>
                <%= image_tag("panic.png", :alt => "Head by Eliricon from the Noun Project", :class => "bulbIcon") %>
                <p>Panic Score:{{bulb.panic_score}}</p>
            </li>

            <ul class=commentList ng-repeat="comment in bulb.comment_data">
                <li>
                    <p>"{{comment.comment}}"</p>
                </li>
            </ul>

    </ul>

    <form class="addComment" name="commentForm">
        <input type="text" name="commentInput" ng-model=bulb.commentText>
        <button type="button" ng-click="timeline.addComment(bulb.commentText, bulb.bulb_id)">Comment</button>
    </form>
    
</div>

</div>